camera:
  width:            480
  height:           272
  viewport_width:   4.8
  viewport_height:  2.72

  pos:    0, 0, 0
  front:  1, 0, 0
  up:     0, 0, 1

  xmin:   -1
  xmax:   1
  ymin:   -1
  ymax:   1
  zmin:   -1
  zmax:   1
